apiVersion: apps/v1
kind: Deployment
metadata:
  name: netsplore-client
  labels:
    app: netsplore-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netsplore-client
  template:
    metadata:
      labels:
        app: netsplore-client
    spec:
      containers:
      - name: netsplore
        image: ghcr.io/noj/netsplore:2025.03.14-1531-6be57317
        command: ["/bin/ipmcread"]
        ports:
        - containerPort: 4000

