apiVersion: apps/v1
kind: Deployment
metadata:
  name: netsplore
  labels:
    app: netsplore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netsplore
  template:
    metadata:
      labels:
        app: netsplore
    spec:
      containers:
      - name: netsplore
        image: ttl.sh/33d22a1d-7833-466a-9aeb-464e80cfc449:8h
        ports:
        - containerPort: 4000

