apiVersion: apps/v1
kind: Deployment
metadata:
  name: netsplore
  labels:
    app: netsplore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netsplore
  template:
    metadata:
      labels:
        app: netsplore
    spec:
      containers:
      - name: netsplore
        image: ghcr.io/noj/netsplore:latest
        command: ["/bin/ipmcsrv"]
        ports:
        - containerPort: 4000

