apiVersion: apps/v1
kind: Deployment
metadata:
  name: netsplore-serve
  labels:
    app: netsplore-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netsplore-serve
  template:
    metadata:
      labels:
        app: netsplore-serve
    spec:
      containers:
      - name: netsplore
        image: ghcr.io/noj/netsplore:2025.03.14-1531-6be57317
        command: ["/bin/ipmcsrv"]
        ports:
        - name: tcp
          containerPort: 4000
        - name: udp
          containerPort: 4001
          protocol: UDP

