apiVersion: v1
kind: Service
metadata:
  name: netsplore-udp
spec:
  selector:
    app: netsplore-serve
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: udp
    port: 4001
    targetPort: 4001
    protocol: UDP
